[build]
  publish = "_site"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run start"
  publish = "_site"
  port = 8080
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Enable Netlify Identity
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"