[build]
  publish = "_site"
  command = "npm run build"

[dev]
  command = "npm run start"
  publish = "_site"
  port = 8080
  
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Enable Netlify Identity for authentication
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"