backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow

# Enable loading of existing values when editing
load_config_file: true
local_backend: true
editor:
  preview: true

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  # Projects Collection
  - name: "projects"
    label: "Projects"
    folder: "src/_projects"
    create: true
    slug: "{{slug}}"
    extension: "md" 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/project.njk" }
      - { label: "Overview", name: "body", widget: "markdown", required: false }
      - label: "Artworks"
        name: "artworks"
        widget: "list"
        summary: "{{fields.title}}"
        allow_add: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Medium", name: "medium", widget: "string" }
          - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
          - { label: "Year", name: "year", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "markdown", required: false }
          - { label: "Display Order", name: "order", widget: "number", default: 1, value_type: "int" }
  
  # Static Pages Collection
  - name: "pages"
    label: "Pages"
    files:
      # Bio Page
      - file: "src/_data/bio.json"
        label: "Bio Page"
        name: "bio"
        editor:
          preview: true
        fields:
          - { label: "Page Header", name: "pageHeader", widget: "string", default: "About Amie" }
          - { label: "Bio Image", name: "bioImage", widget: "image", required: false }
          - { label: "Bio Title", name: "bioTitle", widget: "string", default: "Contemporary Artist" }
          - { label: "Bio Content", name: "bioContent", widget: "markdown" }
          - { label: "Bio Stats", name: "bioStats", widget: "list", required: false, fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Text", name: "text", widget: "string" }
            ] }
          - { label: "Education", name: "education", widget: "list", required: false, fields: [
              { label: "Year", name: "year", widget: "string" },
              { label: "Title", name: "title", widget: "string" },
              { label: "Institution", name: "institution", widget: "string" }
            ] }
          - { label: "Solo Exhibitions", name: "soloExhibitions", widget: "list", required: false, fields: [
              { label: "Year", name: "year", widget: "string" },
              { label: "Title", name: "title", widget: "string" },
              { label: "Location", name: "location", widget: "string" }
            ] }
          - { label: "Residencies & Awards", name: "residenciesAwards", widget: "list", required: false, fields: [
              { label: "Year", name: "year", widget: "string" },
              { label: "Title", name: "title", widget: "string" },
              { label: "Location", name: "location", widget: "string" }
            ] }
          - { label: "Artist Statement", name: "statement", widget: "markdown", required: false }
      # Index Page
      - file: "src/_data/index.json"
        label: "Index Page"
        name: "index"
        editor:
          preview: true
        fields:
          - { label: "Hero Heading", name: "heroHeading", widget: "string", default: "Amie Holstein" }
          - { label: "Hero Text", name: "heroText", widget: "string", default: "Artistic Journey" }
          - { label: "Work Heading", name: "workHeading", widget: "string", default: "Featured Projects" }
          - { label: "CTA Heading", name: "ctaHeading", widget: "string", default: "Interested in collaborating?" }
          - { label: "CTA Text", name: "ctaText", widget: "text", default: "I'm always open to new projects and opportunities to collaborate with other artists, galleries, and art enthusiasts." }
          - { label: "CTA Button Text", name: "ctaButtonText", widget: "string", default: "Get in Touch" }
          - { label: "CTA Button Link", name: "ctaButtonLink", widget: "string", default: "/contact/" }
      # Projects Page
      - file: "src/_data/projects.json"
        label: "Projects Page"
        name: "projects"
        editor:
          preview: true
        fields:
          - { label: "Hero Heading", name: "heroHeading", widget: "string", default: "Projects" }
          - { label: "Hero Text", name: "heroText", widget: "string", default: "A collection of my artistic works and explorations" }

      # 404 Page
      - file: "src/_data/404.json"
        label: "404 Page"
        name: "404"
        editor:
          preview: true
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Page Not Found" }
          - { label: "Message", name: "message", widget: "text", default: "The page you're looking for doesn't seem to exist." }
          - { label: "CTA Text", name: "ctaText", widget: "string", default: "Please check the URL or navigate back to the homepage." }

      # Shop Page
      - file: "src/_data/shop.json"
        label: "Shop Page"
        name: "shop"
        editor:
          preview: true
        fields:
          - { label: "Hero Heading", name: "heroHeading", widget: "string", default: "Shop" }
          - { label: "Hero Text", name: "heroText", widget: "string", default: "Explore unique creations and artistic works available on my Etsy shop, The Sshackk." }
          - { label: "Highlight Heading", name: "highlightHeading", widget: "string", default: "Discover Thesshackk" }
          - { label: "Highlight Text", name: "highlightText", widget: "text", default: "Welcome to The Sshackk, where you can find a curated selection of my artistic creations." }
          - { label: "Highlight Image", name: "highlightImage", widget: "image", default: "/api/placeholder/600/400" }
          - { label: "Highlight Button Text", name: "highlightButtonText", widget: "string", default: "Visit The Sshackk on Etsy" }
          - { label: "Highlight Button Link", name: "highlightButtonLink", widget: "string", default: "https://www.etsy.com/shop/Thesshackk" }

      # Resume Page
      - file: "src/_data/resume.json"
        label: "Resume Page"
        name: "resume"
        editor:
          preview: true
        fields:
          - { label: "Hero Heading", name: "heroHeading", widget: "string", default: "Resume" }
          - { label: "Hero Text", name: "heroText", widget: "string", default: "Professional experience & education" }
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Meta", name: "meta", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
          - { label: "CTA Button Text", name: "ctaButtonText", widget: "string", default: "Download Full CV (PDF)" }
          - { label: "CTA Button Link", name: "ctaButtonLink", widget: "string", default: "#" }

      # Contact Page
      - file: "src/_data/contact.json"
        label: "Contact Page"
        name: "contact"
        editor:
          preview: true
        fields:
          - { label: "Hero Heading", name: "heroHeading", widget: "string", default: "Get In Touch" }
          - { label: "Hero Text", name: "heroText", widget: "text", default: "I'm always interested in new projects, collaborations, and opportunities to share my work." }
          - { label: "Form Heading", name: "formHeading", widget: "string", default: "Send a Message" }
          - label: "Contact Info"
            name: "contactInfo"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
          - label: "Social Links"
            name: "socialLinks"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }